dbt_chanel_test:
  outputs:
    dev:
      dataset: wang_x_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: service-account
      keyfile: 684530330303/secrets/production-deployment-keyfile
      priority: interactive
      project: fshiccaios---inchanelclientapp
      threads: 4
      type: bigquery
    test:
      dataset: test
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: service-account
      keyfile: 684530330303/secrets/production-deployment-keyfile
      priority: interactive
      project: fshiccaios---inchanelclientapp
      threads: 4
      type: bigquery
  target: dev
